[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
publish = false
license-file = "../LICENSE-PROPRIETARY"

[dependencies]
anyhow = "1"
btleplug = "0.12.0"
chrono = "0.4.45"
clap = { version = "4", features = ["derive"] }
futures = "0.3.33"
image = { version = "0.25", default-features = false, features = ["bmp", "png"] }
nusb = "0.1"
pollster = "0.3"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "sync", "signal"] }
uuid = "1.24.0"
